### ISSUE TITLE
Release August 9th, 2023

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#3475]

**Comment by baptisten** [comment]
### LWR
[feature/LWR-266-hyperlink-most-recent-news-title-in-views-reference](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-266-hyperlink-most-recent-news-title-in-views-reference)
- Hyperlink most recent news title in views reference

**Comment by reshmai** [comment]
### Trialcourt
[TCI-1126--SanBenito-Kiosk-iframe-whitelist](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1126--SanBenito-Kiosk-iframe-whitelist)

- Solved SanBenito is not loading into iframe

**Comment by smcgarrigle** [comment]
Is PHP 8 upgrade being tracked anywhere? Archana added it to SRL.

**Comment by melwong-jcc** [comment]
> Is PHP 8 upgrade being tracked anywhere? Archana added it to SRL. @ivanbueno-jcc @melwong-jcc

Is there a reason to upgrade to PHP 8 right now? I know it will be necessary for Drupal 10 so doing it now will help us prepare for D10 but does mean D9 testing as well as a strategy to apply to Pantheon since that change is not done through our process.

In addition, when is the Azure migration occurring which can influence the strategy.

**Comment by ivanbueno-jcc** [comment]
@archanajcc has a backlog ticket for PHP8 upgrade.  There are some composer blockers that need to be resolved first.  It's time to take a look at this ticket again.

Pantheon has been extended for a year, due to the immense cost of Azure.
