### ISSUE TITLE
Release: November 1, 2023

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#3711]
Smoke test plan:
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=53922484

**Comment by melwong-jcc** [comment]
## DCAS
[bugfix/DCAS-175--appearance-setting-mgt](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/DCAS-175--appearance-setting-mgt)
- Corrects theme appearance settings management and deployment setup for elevated sites

**Comment by ivanbueno-jcc** [comment]
[feature/TCI-1173--sb-calendar date](#)
* Fix calendar date formatting of Santa Barbara's criminal calendar

**Comment by reshmai** [comment]
## Newsroom
[NEW-75--image-size-change-featured-news](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/NEW-75--image-size-change-featured-news)

- Image size changed to 16:9 for featured block on homepage

**Comment by archanajcc** [comment]
Trialcourt

[TCI-1171-tentative-ruling-linebreak](#)

**Comment by paboden** [comment]
### Elevated

**DCAS-169 -- Breadcrumbs are displaying twice in some section.**
This code update checks for duplicates in the breadcrumb array and prevents printing the duplicate items.
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3702
Branch - [DCAS-169-breadcrumbs-on-live-are-showing-the-section-items-twice](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-169-breadcrumbs-on-live-are-showing-the-section-items-twice)

---------------

**DCAS-182 -- Update to page html titles on sectioned content**
Previous content followed the "page title | site name" template for the browser page title. This update changes the behavior to sectioned content, to add the section name in between the title and site name ( "page title | section name | site name" )
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3706
Branch - [DCAS-182-page-html-titles](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-182-page-html-titles)

Test:
- Review a page that is applied to a section, and confirm that the browser tab includes the section (district name)

---------------

**DCAS-127 -- feature -- New link setup, including new map link, for ckeditor wysiwyg**
Improves the popup for creating links in ckeditor wysiwyg, with more options for different types of links, including a map link that will open the users preferred map app.
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3704
Branch - [DCAS-127-use-native-mapping-apps-for-court-directions](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-127-use-native-mapping-apps-for-court-directions)

Test:
- Add or Edit an existing page with body/wysiwyg content. Add or Edit a "Map" link via the "insert link" button and check the map triggering functionality.

**Comment by paboden** [comment]
### Elevated

**DCAS-162 and DCAS-181 -- Improve the pathauto settings for section pages**
It changes it to use the parent URL and not the parent menu labels when building the path. It only applies to content NOT defined to already use the section prefix URL. The parent URL will most likely already have the prefix URL applied and it does not need to be reprocessed into the new default pattern.

Also Includes:
- Styles for the active/active-trail menu items in section navigation.
- Caching improvements for section navigation.

PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3702
Branch - [DCAS-169-breadcrumbs-on-live-are-showing-the-section-items-twice](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-169-breadcrumbs-on-live-are-showing-the-section-items-twice)

**Instructions:**
1. Delete all “Content” auto aliases. (/admin/config/search/path/delete_bulk)
2. Run the Bulk generate for content with the “Regenerate URL aliases for all paths” setting (/admin/config/search/path/update_bulk)
3. Run the Bulk generate again with the “Update the URL alias for paths having an old URL alias” settings
4. Run step 3 at least 2-3 times until no more items are updated. Due to the way that pages use the parent url in the template, it is possible that a child page is updated before the proper parent URL has been set. Running the “update old alias” option 2-3 times helps to get around this.

**Test**
- Run above steps
- Click thru different sections and non-sections and confirm that the pages follow the desired pattern. 
- If any Off pages are found, it is most likely due to the auto-generate option turned off on that node. Either it was manually updated on the node or menu item, and the auto-generate option should be reenabled or the link manually updated.

**Comment by Ravi-jud** [comment]
Ticket: https://judasdg.atlassian.net/browse/DCAS-155
PR:
